# SonarCloud — cobertura JaCoCo (Fase 1 + Fase 2)
sonar.host.url=https://sonarcloud.io
sonar.java.source=17
sonar.coverage.jacoco.xmlReportPaths=\
ms-flota-rest/target/site/jacoco/jacoco.xml,\
ms-taller-rest/target/site/jacoco/jacoco.xml,\
ms-clientes/target/site/jacoco/jacoco.xml,\
ms-pedidos/target/site/jacoco/jacoco.xml,\
ms-ruteo/target/site/jacoco/jacoco.xml,\
ms-seguimiento/target/site/jacoco/jacoco.xml,\
ms-auth/target/site/jacoco/jacoco.xml,\
graphql-gateway/target/site/jacoco/jacoco.xml
# Excluir archivos de documentación
sonar.exclusions=**/*.md
