server:
  port: 8082

spring:
  application:
    name: ms-taller-rest
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/logiflow_taller}
    username: ${SPRING_DATASOURCE_USERNAME:logiflow_taller}
    password: ${SPRING_DATASOURCE_PASSWORD:taller_secret}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logiflow:
  flota:
    base-url: http://localhost:8081

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
