server:
  port: 8087

spring:
  application:
    name: ms-seguimiento
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:logiflow}
    password: ${RABBITMQ_PASS:logiflow}
